import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="h-16 bg-yellow-300 flex ">
          <form action="/items" className="m-auto flex max-w-screen-lg flex-1 gap-4 px-4 ">
          <div className="flex items-center"> {}
              <Link href="/" className="text-yellow-900">Mercado Liebre</Link>
          </div>

            <div className="flex gap-4">
                <input className="flex-1 h-10 px-4 text-gray-900 placeholder-gray-500 bg-white border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-yellow-500 focus:border-transparent" type="text" name="search" placeholder="Buscar en Mercado Libre" />
                <button className="bg-pink-500 hover:bg-blue-600 px-6 py-2 text-white font-semibold rounded-md shadow-md transition duration-300 ease-in-out transform hover:scale-105" type="submit">
                Buscar
                </button>
            </div>

          </form>
        </header>
        <main className="max-w-screen-xl px-4 m-auto">{children}</main>
      </body>
    </html>
  );
}
